// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCWorWBHlQ3PVj2ij8nhXGeIfaEHEjdIU',
    appId: '1:945426671867:web:59bd7e0f440867fa3d685e',
    messagingSenderId: '945426671867',
    projectId: 'list-firebase-e6ab1',
    authDomain: 'list-firebase-e6ab1.firebaseapp.com',
    storageBucket: 'list-firebase-e6ab1.firebasestorage.app',
    measurementId: 'G-XMPJ5NHDHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPRYeMOfvxGDmbXUvwamOlN21lw8e0DF4',
    appId: '1:945426671867:android:035d66511d58ea1f3d685e',
    messagingSenderId: '945426671867',
    projectId: 'list-firebase-e6ab1',
    storageBucket: 'list-firebase-e6ab1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbSfZkebSib30OTFFX9ff4hZhtpuGJtas',
    appId: '1:945426671867:ios:f2ff5825e724b62b3d685e',
    messagingSenderId: '945426671867',
    projectId: 'list-firebase-e6ab1',
    storageBucket: 'list-firebase-e6ab1.firebasestorage.app',
    iosBundleId: 'com.example.list',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbSfZkebSib30OTFFX9ff4hZhtpuGJtas',
    appId: '1:945426671867:ios:f2ff5825e724b62b3d685e',
    messagingSenderId: '945426671867',
    projectId: 'list-firebase-e6ab1',
    storageBucket: 'list-firebase-e6ab1.firebasestorage.app',
    iosBundleId: 'com.example.list',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCWorWBHlQ3PVj2ij8nhXGeIfaEHEjdIU',
    appId: '1:945426671867:web:a9e68aef80e4d7dd3d685e',
    messagingSenderId: '945426671867',
    projectId: 'list-firebase-e6ab1',
    authDomain: 'list-firebase-e6ab1.firebaseapp.com',
    storageBucket: 'list-firebase-e6ab1.firebasestorage.app',
    measurementId: 'G-FJNWXF37LK',
  );
}
